Restore GitHub scope URL for token missing error
This reverts commit 98053a010851fd7fe385ccf819b38c630ab4b399.

When our token expires, we get:

    ==> Fetching meetcleo/cleo/cleo
    Error: uninitialized constant GitHub::ALL_SCOPES_URL
    /opt/homebrew/Library/Taps/meetcleo/homebrew-cleo/github.rb:138:in `api_credentials_error_message'

This should fix that.